apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
  labels:
    vol-type: nfs
spec:
  capacity:
    storage: 15Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs: 
    path: /home/cloud-user 
    server: 172.31.17.167
