apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels: 
    app: sample-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30009
    protocol: TCP
  selector:
    app: sample-service

