apiVersion: v1
kind: Pod
metadata:
  name: pod-helloworld
  labels:
    app: helloworld
spec:
  containers:
  - name: container-docker-node-demo
    image: hodei/sample-service
    ports:
    - name: nodejs-port
      containerPort: 3000
      hostPort: 3000
