apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-helloworld
spec:
  replicas: 8
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers: 
      - name: pod-helloworld
        image: taupoali/docker-node-demo:latest
        ports:
        - containerPort: 3000

