apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels: 
    app: helloworld
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30001
    protocol: TCP
  selector:
    app: helloworld

