apiVersion: v1
kind: Pod
metadata:
  name: pod-hello-world
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world
    image: hodei/hello-world
    ports:
    - name: nodeappport
      containerPort: 8080



  
