apiVersion: v1
kind: Service
metadata:
  name: service-testnodeapp
  labels: 
    app: testnodeapp
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30010
    protocol: TCP
  selector:
    app: testnodeapp

